package com.saikumar.expensetracker.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "merchant_aliases")
data class MerchantAlias(
    @PrimaryKey val rawName: String,
    val canonicalName: String,
    val isAutoGenerated: Boolean = true
)
