// Auto-generated merchant mappings
val ML_DETECTED_MERCHANTS = mapOf(
    "CREDIT CARD STATEMENT" to "Credit Bill Payments",
    "CRED CLUB" to "P2P Transfers",
    "PAYTMQR5VL8XR" to "Offline Merchant",
    "ELIORINDIAFOODS90 RZP" to "Miscellaneous",
    "PAYTMQR281005050101A7VEQ4NKST4P" to "Offline Merchant",
    "PAYTMQR5KGT16" to "Offline Merchant",
    "GODALA VIKAS RE" to "P2P Transfers",
    "GODALA VIKAS REDDY" to "P2P Transfers",
    "SAIKUMAR REDDY" to "P2P Transfers",
    "SWIGGY" to "Food Delivery",
    "GODALA SIRISHA" to "P2P Transfers",
    "AMAZON PAY IN E" to "Shopping",
    "A MANOHARACHARI" to "P2P Transfers",
    "Q416761384" to "Offline Merchant",
    "PARAMPARA MITHAI SHOP BHEL MIG" to "Miscellaneous",
    "SAIKUMAR REDDY GODALA" to "P2P Transfers",
    "BOOKMYSHOW" to "Miscellaneous",
    "IND" to "Miscellaneous",
    "ZOMATO" to "Food Delivery",
    "NETFLIX" to "Entertainment",
    "GOOGLE PLAY" to "Miscellaneous",
    "AIRTEL PAYM" to "Mobile + WiFi",
    "UDEMY SUBSCRIPT" to "Education",
    "CP ZEPTO13A87" to "Groceries",
    "AMAZON INDIA CY" to "Shopping",
    "PAYTMQR6MQYK9" to "Offline Merchant",
    "RANGINENI MOUNI" to "P2P Transfers",
    "PAYTMQR669IP3" to "Offline Merchant",
    "GADDAM CHANDI PRIYA" to "P2P Transfers",
    "Q267807266" to "Offline Merchant",
    "ADOBE SYSTEMS S" to "Miscellaneous",
    "PINELABS STQ2737331" to "Miscellaneous",
    "MEKALA NIVAS" to "P2P Transfers",
    "YOUTUBE CYBS" to "Entertainment",
    "PAYTMQR68TVM8" to "Offline Merchant",
    "ZERODHA BROKING LIMITED" to "Mutual Funds",
    "PARIGI DURGAPRASAD" to "P2P Transfers",
    "PRATIKSHA" to "P2P Transfers",
    "REVANTH" to "P2P Transfers",
    "Q873033518" to "Offline Merchant",
    "ICCL ZERODHA" to "Mutual Funds",
    "VAJRAPU SUVARNA PRAKASH" to "P2P Transfers",
    "AMAZON" to "Shopping",
    "CREDPAY UBCP" to "Credit Bill Payments",
    "Q315045812" to "Offline Merchant",
    "SCRATCHBOARDS" to "Miscellaneous",
    "RANGINENI MOUNIKA" to "P2P Transfers",
    "PAYTMQR5Y5AC5" to "Offline Merchant",
    "AVENUE SUPERMAR" to "Groceries",
    "SHIVA KRISHNA NALUMASU" to "P2P Transfers",
    "DINEOUT" to "Dining Out",
    "PRIYANSHU SINGH SO RAMESH SINGH" to "P2P Transfers",
    "VAJRAPU SUVARNA" to "P2P Transfers",
    "ELIOR INDIA FOOD SERVICES LLP" to "Miscellaneous",
    "VANKA SREE SATYA" to "P2P Transfers",
    "HYDMETROINAPP" to "Miscellaneous",
    "BLINKIT PAYU" to "Groceries",
    "ICICI" to "Miscellaneous",
    "GATTAGONI PRANE" to "P2P Transfers",
    "HAZEL NUTS" to "P2P Transfers",
    "AMAZON PAY BALANCE" to "Shopping",
    "SHIVA KRISHNA N" to "P2P Transfers",
    "APSRTC" to "P2P Transfers",
    "PARIGI DURGAPRA" to "P2P Transfers",
    "GOOGLE PLAY APP" to "Miscellaneous",
    "Q306515423" to "Offline Merchant",
    "CREDCLUB" to "P2P Transfers",
    "PARIMI VENKATA SIVARAMA PAVAN KUMAR" to "P2P Transfers",
    "INSTAMART" to "Groceries",
    "PAYTMQR70UJFN" to "Offline Merchant",
    "Q918863195" to "Offline Merchant",
    "OPEN TEXT TECHNOLOGIES" to "Salary",
    "Q462284511" to "Offline Merchant",
    "Q303551895" to "Offline Merchant",
    "GODALA SAIKUMAR REDDY" to "Self Transfer",
    "Q933297054" to "Offline Merchant",
    "SVMBOWLING 67079608" to "Miscellaneous",
    "ADOBE PREMIERE" to "Miscellaneous",
    "Q293804385" to "Offline Merchant",
    "VIKASH MOHAPATRA" to "P2P Transfers",
    "IRCTCPGONLINE" to "Travel",
    "PPSL*SWIGGY" to "Food Delivery",
    "INSTAM" to "Miscellaneous",
    "PAYTMQR2810050501011LM4L9GEAKOS" to "Offline Merchant",
    "TELANGANA STATE ROAD TRANSPORT CORPORATION" to "Miscellaneous",
    "CAFE NILOUFER HITEC CITY" to "Miscellaneous",
    "M S PHOTOKING RETAIL" to "P2P Transfers",
    "GREENTRENDS 63455915" to "Miscellaneous",
    "DECATHLON" to "Miscellaneous",
    "SHIVAM TIWARI" to "P2P Transfers",
    "SHOPSAMS" to "Miscellaneous",
    "FLOSLEEPSOLUTIO514248 RZP" to "Miscellaneous",
    "VR FUELS" to "Fuel",
    "CHAKALI HARINDR" to "P2P Transfers",
    "ELIOR INDIA FOO" to "P2P Transfers",
    "NALBHEEMA KITCH" to "P2P Transfers",
    "VIJAYA RAGHAVEN" to "P2P Transfers",
    "CH MRUDULA PRAN" to "P2P Transfers",
    "NALABHEEMA KITC" to "P2P Transfers",
    "PARIMI VENKATA" to "P2P Transfers",
    "AMAZON INDIA" to "Shopping",
    "FUND IDFC FIRST" to "P2P Transfers",
    "DEVIRADERS" to "Miscellaneous",
    "ABHIBUS586028 RZP" to "Miscellaneous",
    "SRI SAI MEDICAL" to "P2P Transfers",
    "VANKAYALA NAGA" to "P2P Transfers",
    "MRS AKUTHOTA HY" to "P2P Transfers",
    "BARMA AKSHAY KU" to "P2P Transfers",
    "PINELABS STQ2737332" to "Miscellaneous",
    "Q012996166" to "Offline Merchant",
    "INDIAN CLEARING CORPORATION LTD" to "Mutual Funds",
    "Q364101703" to "Offline Merchant",
    "UTPAL DUTTA" to "P2P Transfers",
    "ZEPTONOW ESBZ" to "Groceries",
    "BHIMCASHBACK" to "Cashback",
    "VANKAYALA LALITHAANNAPURNA" to "P2P Transfers",
    "BAKE CENTRAL" to "Dining Out",
    "SHIVKUMAR" to "P2P Transfers",
    "VANKAYALA NAGA SRIVENKATA" to "P2P Transfers",
    "MYNTRA2 PAYU" to "Shopping",
    "AISHWARYA RAO" to "P2P Transfers",
    "YOUTUBEGOOGLE" to "Entertainment",
    "VAJRAPU SUVARNA PRAK" to "P2P Transfers",
    "Q354553035" to "Offline Merchant",
    "REDBUS INDIA PRIVATE LIMITED" to "Travel",
    "SWIGGY8" to "Food Delivery",
    "CF LICIOUS" to "Food Delivery",
    "LICIOUS" to "Food Delivery",
    "Q550433852" to "Offline Merchant",
    "MAHARAJA CHAT AND FOODS" to "Dining Out",
    "GAMEONLEVELUPYOURFUN 63978483" to "Entertainment",
    "KOMALIVANKAYALA" to "P2P Transfers",
    "PRIVEPLEX734888 RZP" to "Entertainment",
    "ADHOC SIVAM AUTO HITEC" to "Service",
    "MD ASIF AHMED" to "P2P Transfers",
    "KALALU KAMALAKAR GOUD" to "P2P Transfers",
    "NAGIREDDYSHIRISHA9" to "P2P Transfers",
    "NEERUDI SRINIVAS" to "P2P Transfers",
    "Q493415905" to "Offline Merchant",
    "Q321074876" to "Offline Merchant",
    "Q527092765" to "Offline Merchant",
    "Q409450589" to "Offline Merchant",
    "PAYTMQR64IJP3" to "Offline Merchant",
    "DOT GAME" to "P2P Transfers",
    "Q403609456" to "Offline Merchant",
    "Q283292883" to "Offline Merchant",
    "LASTHOUSECOFFEE 96120121" to "Miscellaneous",
    "BLINKITJKB RZP" to "Groceries",
    "Q828848254" to "Offline Merchant",
    "R KALAI ARASAN" to "P2P Transfers",
    "SWIGGY319952 RZP" to "Food Delivery",
    "GOKHANA PAYU" to "Miscellaneous",
    "IBKPOS EP030023" to "Miscellaneous",
    "KUNCHAPU KOTAIAH" to "P2P Transfers",
    "Q520732982" to "Offline Merchant",
    "ASHTURI SHEKAR" to "P2P Transfers",
    "PAYTMQRBCT70SICNU" to "Offline Merchant",
    "YAVARNA SATHISH" to "P2P Transfers",
    "MAYANK TYAGI" to "P2P Transfers",
    "VIKASH MOHAPATR" to "P2P Transfers",
    "TATAPAYMENTS MUM" to "Miscellaneous",
    "P NARESH" to "P2P Transfers",
    "ZAIKA RESTAURANT" to "Miscellaneous",
    "MANDIKINGARABIANREST 66032690" to "Dining Out",
    "COMMISSIONER OF POLICE HYDERABAD CITY" to "Insurance",
    "THIRUMALABABU429" to "P2P Transfers",
    "DDKPRIYANKA" to "P2P Transfers",
    "MEKALANIVAS" to "P2P Transfers",
    "ABENAI TAMANG" to "P2P Transfers",
    "CASSWIGGY" to "Food Delivery",
    "PAYTMQR2810050501011TX419RQLZJN" to "Offline Merchant",
    "PAYTMQR6LIG13" to "Offline Merchant",
    "Q972173496" to "Offline Merchant",
    "RUKSANA KHATOON" to "P2P Transfers",
    "Q401040298" to "Offline Merchant",
    "AMOEBA" to "Miscellaneous",
    "BOOKMYS" to "Miscellaneous",
    "ZEEENTERTAINMEN" to "Miscellaneous",
    "M23ZWGI44VJYX" to "Miscellaneous",
    "BLINKIT RZP" to "Groceries",
    "GOOGLEPLAY" to "Miscellaneous",
    "THE NAWAABS RESTAURANT" to "Dining Out",
    "Q704795785" to "Offline Merchant",
    "JOGU PRABHU" to "P2P Transfers",
    "Q122398742" to "Offline Merchant",
    "TARUNTEJA2728" to "P2P Transfers",
    "8247610779TB" to "P2P Transfers",
    "VALVECORPORATIO111765 RZP" to "Miscellaneous",
    "EKART" to "Miscellaneous",
    "PAVANTM1" to "P2P Transfers",
    "MOHAMMEDIMRAN201198" to "P2P Transfers",
    "DISTRICT MOVIES" to "Miscellaneous",
    "SPUDATOFOODS 69331479" to "Miscellaneous",
    "FLIPKART" to "Shopping",
    "RAJAKULLAYAPPA GUDURU" to "P2P Transfers",
    "GROFERS1PAYTM" to "Miscellaneous",
    "Q741318349" to "Offline Merchant",
    "THE GREAT WALL" to "P2P Transfers",
    "LOHITHA PUTHA" to "P2P Transfers",
    "PAYTMQRC8W3AHVSWN" to "Offline Merchant",
    "Q919100457" to "Offline Merchant",
    "AMAZON PAY" to "Shopping",
    "GATTAGONI PRANEETH KUMAR" to "P2P Transfers",
    "SIRIKOTI PAVAN KUMAR" to "P2P Transfers",
    "CBDT" to "P2P Transfers",
    "DEFMACRO SOFTWARE PRIVATE LIMITED" to "Miscellaneous",
    "ZEPTOONLINE" to "Groceries",
    "Q295496179" to "Offline Merchant",
    "ADHOC SIVAM AUT" to "Miscellaneous",
    "PAVAN PARIMI1" to "P2P Transfers",
    "Q511578012" to "Offline Merchant",
    "Q639492524" to "Offline Merchant",
    "V N S V L ANNAPURNA" to "P2P Transfers",
    "LALITHAANNAPURNA97 1" to "P2P Transfers",
    "SRI JAIN JEWEL PARK" to "P2P Transfers",
    "SRI JAIN JEWEL" to "P2P Transfers",
    "YUM RESTAURANT" to "P2P Transfers",
    "MOTHUKULA SRIRAMULU" to "P2P Transfers",
    "ERLA YESUBABU" to "P2P Transfers",
    "PAYTMQRCBCNGYRJOB" to "Offline Merchant",
    "DBHAGYARAJU 2" to "P2P Transfers",
    "GODALASAIKUMAR1" to "P2P Transfers",
    "SUNIL TULASIRAM RATHOD" to "P2P Transfers",
    "REGLOBE" to "P2P Transfers",
    "M VENKATESH" to "P2P Transfers",
    "INFINITI RETAIL LIMITEMUM" to "Miscellaneous",
    "Q616372436" to "Offline Merchant",
    "FLIPKART1278033 06M" to "Shopping",
    "KUPPALA JOSEPH" to "P2P Transfers",
    "MALLADI ANIL" to "P2P Transfers",
    "MR MOHAMMED KHA" to "P2P Transfers",
    "ZERODHA BROKING LTD" to "Mutual Funds",
    "ZERODHA BROKING" to "P2P Transfers",
    "SRINIVAS GOUD" to "P2P Transfers",
    "RATHOD REDYA NA" to "P2P Transfers",
    "KONDURU JASWANT" to "P2P Transfers",
    "BASA RAMA KRISH" to "P2P Transfers",
    "SWIGGYSTORES" to "Food Delivery",
    "GOIBIBO1ONLINE GPAY" to "Miscellaneous",
    "ORSU RAJU" to "P2P Transfers",
    "BLINKIT728236 RZP" to "Groceries",
    "KOTA MADHAVI" to "P2P Transfers",
    "SWIGGY STORES" to "Food Delivery",
    "MOHAMMAD IMAMUL" to "P2P Transfers",
    "SRI L V MOTORS" to "Miscellaneous",
    "CREDPAY LICIOUS" to "Food Delivery",
    "SMARTSHIFTONLINE" to "Miscellaneous",
    "THANNERU THARUN" to "P2P Transfers",
    "MR RAMAVATH SRI" to "P2P Transfers",
    "PAYTMQR6JGQGN" to "Offline Merchant",
    "GADHE BABU" to "P2P Transfers",
    "PAYTMQR6CLXV5" to "Offline Merchant",
    "BEJJAM ASHOK" to "P2P Transfers",
    "PAYTMQR30L9OGL006" to "Offline Merchant",
    "BANDARI RAMANAD" to "P2P Transfers",
    "SHEKHAR RAPOLU" to "P2P Transfers",
    "PAPPULA SIDDHAR" to "P2P Transfers",
    "BLINKIT3 PAYU" to "Groceries",
    "KPN FF 2012 KOT" to "Miscellaneous",
    "Q910858773" to "Offline Merchant",
    "PINELABS 10511000" to "Miscellaneous",
    "PAYTMQR6B0KJY" to "Offline Merchant",
    "PAYTMQR6B2SKV" to "Offline Merchant",
    "PRAVAH SOCIAL S" to "P2P Transfers",
    "MVR ENTERPRISES" to "P2P Transfers",
    "Q668651149" to "Offline Merchant",
    "PAYTMQR6EVYVU" to "Offline Merchant",
    "SHAIK MOHAMMED" to "P2P Transfers",
    "THATUGARI RAMU" to "P2P Transfers",
    "MOHAMMED IRFAN" to "P2P Transfers",
    "MOHD GHOUSE" to "P2P Transfers",
    "SIVANI ENTERPRISES" to "Miscellaneous",
    "VENKAT REDDY MA" to "Miscellaneous",
    "Q868002243" to "Offline Merchant",
    "CH MRUDULA PRANATHI" to "P2P Transfers",
    "KETHAVATH NARES" to "P2P Transfers",
    "BVKFOODCOURTS 66035880" to "Miscellaneous",
    "KORRA SRIKANTH" to "P2P Transfers",
    "WWW POLICYBAZAAR COM" to "P2P Transfers",
    "SOMAIAH" to "P2P Transfers",
    "Q231451563" to "Offline Merchant",
    "SHIVALIK SMALL FINANCE BANK LTD" to "Miscellaneous",
    "TATAPAYMENTSLIMITE" to "Miscellaneous",
    "SURYODAY SMALL FINANCE BANK" to "Miscellaneous",
    "ZEPTO MARKETPLA" to "Groceries",
    "PRASADS 63402203" to "Miscellaneous",
    "TUMBALI SANDEEP KUMAR" to "P2P Transfers",
    "PAYTMQR14TZ6NCJWE" to "Offline Merchant",
    "CREDPAY IRCTC" to "Travel",
    "UPPARI KESAVULU" to "P2P Transfers",
    "PINELABS 10139805" to "Miscellaneous",
    "M S COFFEE IDEAS" to "Miscellaneous",
    "MAB 037347035480029" to "Miscellaneous",
    "TTDCLBOATHOUSE 76043271" to "Miscellaneous",
    "RAJA K" to "P2P Transfers",
    "PAYTMQR66X13A" to "Offline Merchant",
    "Q127212279" to "Offline Merchant",
    "AJITH M" to "P2P Transfers",
    "Q600745340" to "Offline Merchant",
    "Q229664853" to "Offline Merchant",
    "Q836664158" to "Offline Merchant",
    "Q537000303" to "Offline Merchant",
    "PHONEPEBSNLSOUTH" to "Mobile + WiFi",
    "MR GODALA SAIKUMAR" to "Self Transfer",
    "Q442677469" to "Offline Merchant",
    "YUGANDHAR REDDY GODALA" to "P2P Transfers",
    "HINDUSTAN PETRO" to "Miscellaneous",
    "CREAM STONE CRE" to "P2P Transfers",
    "PRASADS 63402198" to "Miscellaneous",
    "KORE SAI KIRAN" to "P2P Transfers",
    "GUNDLAPALLI SRU" to "P2P Transfers",
    "NENAVATH RAMLAL" to "P2P Transfers",
    "SYED ABDUL MUBE" to "P2P Transfers",
    "SABAVAT LAXMIPA" to "P2P Transfers",
    "KONAM UPENDAR" to "P2P Transfers",
    "BELLISSIMO SALO" to "P2P Transfers",
    "BANAVATH THARUN" to "P2P Transfers",
    "MOHD SHAIBAAZ" to "P2P Transfers",
    "MOHAMMAD SHAMSH" to "P2P Transfers",
    "SYED AIJAZ KHAD" to "P2P Transfers",
    "SWIGGYDINEIN" to "Food Delivery",
    "MUDAVATH RAVI N" to "P2P Transfers",
    "DHANAVATH SIKIN" to "P2P Transfers",
    "DISTRICTDINING PAYU" to "Miscellaneous",
    "AMBOJI SHIVA RA" to "P2P Transfers",
    "YUM YUM TREE ARABIAN FOOD COURT" to "Miscellaneous",
    "VIJAYA KRISHNA ENTERPRISES" to "Miscellaneous",
    "K ARPITHA" to "P2P Transfers",
    "SIRI KOONA" to "P2P Transfers",
    "NILKAMALFURNITU65 RZP" to "Miscellaneous",
    "NALLIBOINA THIR" to "P2P Transfers",
    "ABHINAV KOSTA S" to "P2P Transfers",
    "VORSU SATHYA LA" to "P2P Transfers",
    "SANDEPALU MADHU" to "P2P Transfers",
    "JAGAPATHI BABU AREM" to "P2P Transfers",
    "KOLUGURI KRISHN" to "P2P Transfers",
    "KONDA MADUGULA VEERA NARENDRA NATH" to "P2P Transfers",
    "RAJA SHEKER" to "P2P Transfers",
    "TANDA SURESH" to "P2P Transfers",
    "JATOTHU VIJAYA KUMARI" to "P2P Transfers",
    "GUGULOTH SANDEE" to "P2P Transfers",
    "NAGIREDDY VENUG" to "P2P Transfers",
    "GUNDALA GANGADH" to "P2P Transfers",
    "PAYTMQR67OGNW" to "Offline Merchant",
    "GANTA SANDEEP K" to "P2P Transfers",
    "PAYTMQR68VMIT" to "Offline Merchant",
    "AMBOJI SHIVARAJ" to "P2P Transfers",
    "INVESTTIN559791 RZP" to "Miscellaneous",
    "MRUDULAPRANATHISAI" to "P2P Transfers",
    "GODALA SAIDULU" to "P2P Transfers",
    "IRUGUDINDLA VEN" to "P2P Transfers",
    "SONA BAKERY" to "P2P Transfers",
    "AZMATH" to "P2P Transfers",
    "PAYTMQR6197SW" to "Offline Merchant",
    "B MALLESH" to "P2P Transfers",
    "ALEKHYA DIAGNOS" to "P2P Transfers",
    "MEDIBUDDY PHASO" to "P2P Transfers",
    "POLAMURI SUDHIR" to "P2P Transfers",
    "Q676547638" to "Offline Merchant",
    "KODAVATH RAMULU" to "P2P Transfers",
    "Q923269687" to "Offline Merchant",
    "YASHODASUPERSPECIALI 42580946" to "Miscellaneous",
    "SBI CARDS AND" to "Other Income",
    "WAKEFIT" to "Miscellaneous",
    "NUNEMUNTHALA NA" to "P2P Transfers",
    "PRABHAKAR DODDI" to "P2P Transfers",
    "GUNDEKARI HARISH" to "P2P Transfers",
    "NUNSAVATH GOPAL" to "P2P Transfers",
    "SIVANI ENTERPRI" to "P2P Transfers",
    "BADA GOUNI SREENIVAS GOUD" to "P2P Transfers",
    "MAMATHA CH" to "P2P Transfers",
    "SOUTH INDIA JEW" to "Miscellaneous",
    "CREDPAYZEPTO" to "P2P Transfers",
    "JAMALPURI SAI K" to "P2P Transfers",
    "HARISH C" to "P2P Transfers",
    "GODALA VIKAS VI" to "P2P Transfers",
    "EENADU TELEVISI" to "P2P Transfers",
    "J VIVEK JAISWAL" to "P2P Transfers",
    "SUDHAKAR REDDY" to "P2P Transfers",
)
